import { NextResponse } from 'next/server';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const query = searchParams.get('query') || '';

  const allSkills = [
    { id: 1, name: "JavaScript" },
    { id: 2, name: "TypeScript" },
    { id: 3, name: "React" },
    { id: 4, name: "Angular" },
    { id: 5, name: "Vue.js" },
    { id: 6, name: "Node.js" },
    { id: 7, name: "Python" },
    { id: 8, name: "Java" },
    { id: 9, name: "C#" },
    { id: 10, name: "C++" },
    { id: 11, name: "Go" },
    { id: 12, name: "Rust" },
    { id: 13, name: "PHP" },
    { id: 14, name: "Ruby" },
    { id: 15, name: "Swift" },
    { id: 16, name: "Kotlin" },
    { id: 17, name: "Scala" },
    { id: 18, name: "Dart" },
    { id: 19, name: "HTML" },
    { id: 20, name: "CSS" },
    { id: 21, name: "Sass" },
    { id: 22, name: "Less" },
    { id: 23, name: "Tailwind CSS" },
    { id: 24, name: "Bootstrap" },
    { id: 25, name: "Material-UI" },
    { id: 26, name: "Ant Design" },
    { id: 27, name: "Next.js" },
    { id: 28, name: "Nuxt.js" },
    { id: 29, name: "Gatsby" },
    { id: 30, name: "Express.js" },
    { id: 31, name: "FastAPI" },
    { id: 32, name: "Django" },
    { id: 33, name: "Flask" },
    { id: 34, name: "Spring Boot" },
    { id: 35, name: "ASP.NET Core" },
    { id: 36, name: "Laravel" },
    { id: 37, name: "Ruby on Rails" },
    { id: 38, name: "GraphQL" },
    { id: 39, name: "REST API" },
    { id: 40, name: "MongoDB" },
    { id: 41, name: "PostgreSQL" },
    { id: 42, name: "MySQL" },
    { id: 43, name: "Redis" },
    { id: 44, name: "Elasticsearch" },
    { id: 45, name: "Docker" },
    { id: 46, name: "Kubernetes" },
    { id: 47, name: "AWS" },
    { id: 48, name: "Azure" },
    { id: 49, name: "Google Cloud" },
    { id: 50, name: "Firebase" },
    { id: 51, name: "Git" },
    { id: 52, name: "GitHub" },
    { id: 53, name: "GitLab" },
    { id: 54, name: "Bitbucket" },
    { id: 55, name: "Jenkins" },
    { id: 56, name: "CircleCI" },
    { id: 57, name: "GitHub Actions" },
    { id: 58, name: "Jest" },
    { id: 59, name: "Cypress" },
    { id: 60, name: "Selenium" },
    { id: 61, name: "Playwright" },
    { id: 62, name: "Webpack" },
    { id: 63, name: "Vite" },
    { id: 64, name: "Rollup" },
    { id: 65, name: "Babel" },
    { id: 66, name: "ESLint" },
    { id: 67, name: "Prettier" },
    { id: 68, name: "Husky" },
    { id: 69, name: "Lint-staged" },
    { id: 70, name: "Storybook" },
    { id: 71, name: "Figma" },
    { id: 72, name: "Sketch" },
    { id: 73, name: "Adobe XD" },
    { id: 74, name: "InVision" },
    { id: 75, name: "Zeplin" },
    { id: 76, name: "Machine Learning" },
    { id: 77, name: "Deep Learning" },
    { id: 78, name: "TensorFlow" },
    { id: 79, name: "PyTorch" },
    { id: 80, name: "Scikit-learn" },
    { id: 81, name: "Pandas" },
    { id: 82, name: "NumPy" },
    { id: 83, name: "Matplotlib" },
    { id: 84, name: "Seaborn" },
    { id: 85, name: "Jupyter" },
    { id: 86, name: "Data Analysis" },
    { id: 87, name: "Data Visualization" },
    { id: 88, name: "Tableau" },
    { id: 89, name: "Power BI" },
    { id: 90, name: "Looker" },
    { id: 91, name: "Apache Spark" },
    { id: 92, name: "Hadoop" },
    { id: 93, name: "Kafka" },
    { id: 94, name: "RabbitMQ" },
    { id: 95, name: "Apache Airflow" },
    { id: 96, name: "Terraform" },
    { id: 97, name: "Ansible" },
    { id: 98, name: "Chef" },
    { id: 99, name: "Puppet" },
    { id: 100, name: "Prometheus" },
    { id: 101, name: "Grafana" },
    { id: 102, name: "Datadog" },
    { id: 103, name: "New Relic" },
    { id: 104, name: "Sentry" },
    { id: 105, name: "LogRocket" },
    { id: 106, name: "Mixpanel" },
    { id: 107, name: "Amplitude" },
    { id: 108, name: "Google Analytics" },
    { id: 109, name: "Hotjar" },
    { id: 110, name: "Optimizely" },
    { id: 111, name: "A/B Testing" },
    { id: 112, name: "SEO" },
    { id: 113, name: "SEM" },
    { id: 114, name: "Google Ads" },
    { id: 115, name: "Facebook Ads" },
    { id: 116, name: "LinkedIn Ads" },
    { id: 117, name: "Email Marketing" },
    { id: 118, name: "Mailchimp" },
    { id: 119, name: "SendGrid" },
    { id: 120, name: "HubSpot" },
    { id: 121, name: "Salesforce" },
    { id: 122, name: "Zendesk" },
    { id: 123, name: "Intercom" },
    { id: 124, name: "Slack" },
    { id: 125, name: "Microsoft Teams" },
    { id: 126, name: "Discord" },
    { id: 127, name: "Zoom" },
    { id: 128, name: "Google Meet" },
    { id: 129, name: "Notion" },
    { id: 130, name: "Confluence" },
    { id: 131, name: "Trello" },
    { id: 132, name: "Asana" },
    { id: 133, name: "Jira" },
    { id: 134, name: "Linear" },
    { id: 135, name: "ClickUp" },
    { id: 136, name: "Monday.com" },
    { id: 137, name: "Airtable" },
    { id: 138, name: "Zapier" },
    { id: 139, name: "IFTTT" },
    { id: 140, name: "Make" },
    { id: 141, name: "n8n" },
    { id: 142, name: "Stripe" },
    { id: 143, name: "PayPal" },
    { id: 144, name: "Square" },
    { id: 145, name: "Shopify" },
    { id: 146, name: "WooCommerce" },
    { id: 147, name: "Magento" },
    { id: 148, name: "BigCommerce" },
    { id: 149, name: "Squarespace" },
    { id: 150, name: "Wix" },
    { id: 151, name: "WordPress" },
    { id: 152, name: "Drupal" },
    { id: 153, name: "Joomla" },
    { id: 154, name: "Ghost" },
    { id: 155, name: "Medium" },
    { id: 156, name: "Substack" },
    { id: 157, name: "Twilio" },
    { id: 158, name: "SendGrid" },
    { id: 159, name: "Mailgun" },
    { id: 160, name: "AWS SES" },
    { id: 161, name: "Cloudflare" },
    { id: 162, name: "Akamai" },
    { id: 163, name: "Fastly" },
    { id: 164, name: "Vercel" },
    { id: 165, name: "Netlify" },
    { id: 166, name: "Heroku" },
    { id: 167, name: "DigitalOcean" },
    { id: 168, name: "Linode" },
    { id: 169, name: "Vultr" },
    { id: 170, name: "Algolia" },
    { id: 171, name: "Elasticsearch" },
    { id: 172, name: "Meilisearch" },
    { id: 173, name: "Typesense" },
    { id: 174, name: "QStash" },
    { id: 175, name: "Upstash" },
    { id: 176, name: "PlanetScale" },
    { id: 177, name: "Supabase" },
    { id: 178, name: "Appwrite" },
    { id: 179, name: "Sanity" },
    { id: 180, name: "Strapi" },
    { id: 181, name: "Contentful" },
    { id: 182, name: "Prismic" },
    { id: 183, name: "ButterCMS" },
    { id: 184, name: "Storyblok" },
    { id: 185, name: "Framer" },
    { id: 186, name: "Webflow" },
    { id: 187, name: "Bubble" },
    { id: 188, name: "Glide" },
    { id: 189, name: "Adalo" },
    { id: 190, name: "OutSystems" },
    { id: 191, name: "Mendix" },
    { id: 192, name: "Power Apps" },
    { id: 193, name: "Retool" },
    { id: 194, name: "Budibase" },
    { id: 195, name: "Appsmith" },
    { id: 196, name: "Tooljet" },
    { id: 197, name: "N8N" },
    { id: 198, name: "Node-RED" },
    { id: 199, name: "Zapier" },
    { id: 200, name: "Make" }
  ];

  // Filter skills based on query if provided
  const filteredSkills = query
    ? allSkills.filter(skill =>
        skill.name.toLowerCase().includes(query.toLowerCase())
      )
    : allSkills;

  return NextResponse.json(filteredSkills);
}
