import { NextResponse } from 'next/server';

export async function GET() {
  const designations = [
    { id: 1, name: "Software Engineer" },
    { id: 2, name: "Senior Software Engineer" },
    { id: 3, name: "Lead Software Engineer" },
    { id: 4, name: "Software Architect" },
    { id: 5, name: "Frontend Developer" },
    { id: 6, name: "Backend Developer" },
    { id: 7, name: "Full Stack Developer" },
    { id: 8, name: "DevOps Engineer" },
    { id: 9, name: "Data Scientist" },
    { id: 10, name: "Data Engineer" },
    { id: 11, name: "Machine Learning Engineer" },
    { id: 12, name: "Product Manager" },
    { id: 13, name: "Senior Product Manager" },
    { id: 14, name: "Product Owner" },
    { id: 15, name: "Scrum Master" },
    { id: 16, name: "Project Manager" },
    { id: 17, name: "Program Manager" },
    { id: 18, name: "Engineering Manager" },
    { id: 19, name: "Technical Lead" },
    { id: 20, name: "Team Lead" },
    { id: 21, name: "UI/UX Designer" },
    { id: 22, name: "UX Designer" },
    { id: 23, name: "UI Designer" },
    { id: 24, name: "Graphic Designer" },
    { id: 25, name: "Visual Designer" },
    { id: 26, name: "Content Strategist" },
    { id: 27, name: "Content Writer" },
    { id: 28, name: "Copywriter" },
    { id: 29, name: "Marketing Manager" },
    { id: 30, name: "Digital Marketing Specialist" },
    { id: 31, name: "SEO Specialist" },
    { id: 32, name: "Social Media Manager" },
    { id: 33, name: "Sales Manager" },
    { id: 34, name: "Business Development Manager" },
    { id: 35, name: "Account Manager" },
    { id: 36, name: "Customer Success Manager" },
    { id: 37, name: "HR Manager" },
    { id: 38, name: "Recruiter" },
    { id: 39, name: "Talent Acquisition Specialist" },
    { id: 40, name: "Finance Manager" },
    { id: 41, name: "Financial Analyst" },
    { id: 42, name: "Accountant" },
    { id: 43, name: "Operations Manager" },
    { id: 44, name: "Supply Chain Manager" },
    { id: 45, name: "Quality Assurance Engineer" },
    { id: 46, name: "Test Engineer" },
    { id: 47, name: "Security Engineer" },
    { id: 48, name: "Network Engineer" },
    { id: 49, name: "System Administrator" },
    { id: 50, name: "Database Administrator" },
    { id: 51, name: "Business Analyst" },
    { id: 52, name: "Data Analyst" },
    { id: 53, name: "Research Analyst" },
    { id: 54, name: "Legal Counsel" },
    { id: 55, name: "Compliance Officer" },
    { id: 56, name: "Risk Manager" },
    { id: 57, name: "Strategy Manager" },
    { id: 58, name: "Consultant" },
    { id: 59, name: "Senior Consultant" },
    { id: 60, name: "Director" },
    { id: 61, name: "Vice President" },
    { id: 62, name: "Chief Technology Officer" },
    { id: 63, name: "Chief Executive Officer" },
    { id: 64, name: "Chief Financial Officer" },
    { id: 65, name: "Chief Marketing Officer" },
    { id: 66, name: "Chief Operating Officer" },
    { id: 67, name: "Founder" },
    { id: 68, name: "Co-founder" },
    { id: 69, name: "Intern" },
    { id: 70, name: "Graduate Trainee" },
    { id: 71, name: "Junior Developer" },
    { id: 72, name: "Associate" },
    { id: 73, name: "Senior Associate" },
    { id: 74, name: "Principal" },
    { id: 75, name: "Partner" }
  ];

  return NextResponse.json(designations);
}
